main: com.snowleopard1863.APTurrets.TurretsMain
version: 2.2.0
name: APTurrets
description: Allows for player-mounted turrets with support for Movecraft and Worldguard
authors: [snowleopard1863, Senarii, _MrUniverse]
depend: [Movecraft, WorldGuard]
softdepend: [Vault]